theme: jekyll-theme-minimal
title                    : "Canarium Documenation"
title_separator          : "-"
name                     : "Canarium Documenation"
description              : "Getting Started with Canarium Development"
